### ISSUE TITLE
Civo Provider documentation not found 

### ISSUE THREAD

**Issue by DanielCalvo** [civo/terraform-provider-civo#10]
I headed over to https://www.terraform.io/docs/providers/civo/index.html as described on the README.md and nothing :(

Civo also appears to not be listed as a provider: https://www.terraform.io/docs/providers/

**Comment by andyjeffries** [comment]
Thanks for raising this. I think that's in the documentation for when after our community has tested it and we submit it for acceptance in Terraform.

**Comment by alejandrojnm** [comment]
@DanielCalvo you can see the documentation inside https://github.com/civo/terraform-provider-civo/tree/master/website/docs the `r` folder is for the resource and `d` for the datasource. Thanks for the feedback
