### ISSUE TITLE
data source for `civo_firewall`

### ISSUE THREAD

**Issue by surajnarwade** [civo/terraform-provider-civo#112]
as per the provider documentation, I can't see data source for the `civo_firewall`. 

it would be nice to refer existing firewall which is preconfigured with rules.

is there a reason why this data source don't exist.

**Comment by surajnarwade** [comment]
happy to contribute if there's no reason why it does not exist :)

**Comment by saiyam1814** [comment]
Here are docs for creating firewall using terraform 
https://www.civo.com/docs/terraform/598

**Comment by saiyam1814** [comment]
Thanks for raising this @surajnarwade and yes would love your contribution :)

**Comment by surajnarwade** [comment]
Thanks @saiyam1814 PR on it's way soon :)
