### ISSUE TITLE
unexpected state 'AVAILABLE', wanted target 'ACTIVE'. last error: %!s(<nil>)

### ISSUE THREAD

**Issue by dtomasi** [civo/terraform-provider-civo#123]
I got this error earlier this morning and I'm wondering if this is related to the terraform, the provider or CIVO API.

```
│ Error: error waiting for cluster (70e17037-fcf8-4be5-8a9d-xxx[82](https://gitlab.com/xxx/-/jobs/2227#L82)f0e79) to be created: unexpected state 'AVAILABLE', wanted target 'ACTIVE'. last error: %!s(<nil>)
│ 
│   with module.stack.civo_kubernetes_cluster.this,
│   on .terraform/modules/stack/main.tf line 37, in resource "civo_kubernetes_cluster" "this":
│   37: resource "civo_kubernetes_cluster" "this" {
│ 
```

**Comment by haardikdharma10** [comment]
@alejandrojnm can you take a look at this? I think this is coming from - https://github.com/civo/terraform-provider-civo/blob/master/civo/resource_kubernetes_cluster.go#L300

**Comment by alejandrojnm** [comment]
Hi @dtomasi that errar was fixed in the last version, what version are you running??

**Comment by alejandrojnm** [comment]
I will close this one
