### ISSUE TITLE
Crash while refreshing state

### ISSUE THREAD

**Issue by landro** [civo/terraform-provider-civo#126]
civo_kubernetes_cluster.my-cluster: Refreshing state... [id=8ac52eba-5fbd-4279-8567-4e6934c33d88]
╷
│ Error: Plugin did not respond
│
│   with civo_kubernetes_cluster.my-cluster,
│   on main.tf line 50, in resource "civo_kubernetes_cluster" "my-cluster":
│   50: resource "civo_kubernetes_cluster" "my-cluster" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-civo_v1.0.14 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 83 [running]:
github.com/civo/terraform-provider-civo/civo.flattenNodePool(0xc0007b0000, 0xc00019be00, 0x9, 0x19cc1a0, 0xc000610438)
	/home/runner/work/terraform-provider-civo/terraform-provider-civo/civo/resource_kubernetes_cluster.go:567 +0xdd6
github.com/civo/terraform-provider-civo/civo.resourceKubernetesClusterRead(0x1cd4498, 0xc000328f00, 0xc00019be00, 0x1b30380, 0xc0002645f0, 0xc0004aaf00, 0xc000537908, 0x100df38)
	/home/runner/work/terraform-provider-civo/terraform-provider-civo/civo/resource_kubernetes_cluster.go:406 +0xb06
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000573260, 0x1cd4428, 0xc0004e0680, 0xc00019be00, 0x1b30380, 0xc0002645f0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:347 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000573260, 0x1cd4428, 0xc0004e0680, 0xc0003a33b0, 0x1b30380, 0xc0002645f0, 0xc0005047b0, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00000c258, 0x1cd4428, 0xc0004e0680, 0xc0004e06c0, 0xc0004e0680, 0x100b665, 0x1ab5500)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.5.0/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc0004ca140, 0x1cd44d0, 0xc0004e0680, 0xc000328840, 0xc0004ca140, 0xc000633350, 0xc000525ba0)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x1aee300, 0xc0004ca140, 0x1cd44d0, 0xc000633350, 0xc0003287e0, 0x0, 0x1cd44d0, 0xc000633350, 0xc0007a3000, 0xf83)
	/home/runner/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.2.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003ddc00, 0x1cdd418, 0xc000103980, 0xc0001f8200, 0xc00064e1e0, 0x21e4b30, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0003ddc00, 0x1cdd418, 0xc000103980, 0xc0001f8200, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0003f61a0, 0xc0003ddc00, 0x1cdd418, 0xc000103980, 0xc0001f8200)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-civo_v1.0.14 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by alejandrojnm** [comment]
HI, can you share your `tf` file ???

**Comment by alejandrojnm** [comment]
This is already fixed
