### ISSUE TITLE
`region` field in `civo_kubernetes_node_pool` should not be required 

### ISSUE THREAD

**Issue by surajnarwade** [civo/terraform-provider-civo#140]
I think the `region` field in `civo_kubernetes_node_pool` as mentioned below should be optional:

```
resource "civo_kubernetes_node_pool" "back-end" {
   cluster_id = civo_kubernetes_cluster.my-cluster.id
   label = "back-end" // Optional
   node_count = 1 // Optional
   size = element(data.civo_size.xsmall.sizes, 0).name // Optional
   region = "LON1" # Currently required
}
```

As per the docs, the region of node_pool should match the cluster. But in cluster definition, we are already passing `region` and if not passed it is picking it up from the provider definition.

does this make sense? if yes,  I am happy to contribute :)  🙏

**Comment by alejandrojnm** [comment]
Made the PR to see

**Comment by uzaxirr** [comment]
Hey @alejandrojnm 
I'm unable to find PR for this issue can you please link it. And if it's not been made yet i'll be happy to pick it up

**Comment by alejandrojnm** [comment]
I don't remember saw that PR so you can do it, let me know when is done and I will check

**Comment by uzaxirr** [comment]
Hey @alejandrojnm 
My approch would be: 
in `civo/resource_kubernetes_cluster_pool.go` we need to change the region key of the schema to this
```
	"region": {
		Type:         schema.TypeString,
		Required:     false,
		Description:  "The region of the node pool, has to match that of the cluster",
		ValidateFunc: validation.StringIsNotEmpty,
	},
```
But i'm not sure what should be the value of `apiClient.Region` in case region is not specified and the `region` variable in `resourceKubernetesClusterNodePoolCreate` function is nil

**Comment by uzaxirr** [comment]
Raised an initial PR #149 please do give it a look

**Comment by alejandrojnm** [comment]
For now this is not posible
