### ISSUE TITLE
Object Store Docs Missing

### ISSUE THREAD

**Issue by DMajrekar** [civo/terraform-provider-civo#155]
The docs for object store are out of date

```
❯ terraform show
# civo_object_store.template:
resource "civo_object_store" "template" {
    access_key_id = 
    bucket_url    = 
    id            = 
    max_size_gb   = 
    name          = 
    region        =
    status        =
}
```

These fields don't match what is listed on https://registry.terraform.io/providers/civo/civo/latest/docs/resources/object_store

When reading the docs, I would have expected the status output to be documented so I know what I can use in other parts of my tf file.

**Comment by DMajrekar** [comment]
Looks like we're missing the "Attribute" section similar to https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/compute_keypair_v2#attributes-reference

**Comment by alejandrojnm** [comment]
We can't add that section to the doc, because we use `terraform-plugin-docs` to generate the doc for the provider, so we can't touch the doc file because it will be overwritten by the release process.
