### ISSUE TITLE
Issue using Terraform Provider when Upgrading with Existing Cluster

### ISSUE THREAD

**Issue by martynbristow** [civo/terraform-provider-civo#157]
Version: 1.0.26
Previous Version: 1.0.6 ... I've upgraded the provider and resolved issues with management but now the provider crashes:

Log file attached: 

[terraform.txt](https://github.com/civo/terraform-provider-civo/files/10203530/terraform.txt)

Issue appears to be:  `PANIC: interface conversion: interface {} is nil, not string`

**Comment by alejandrojnm** [comment]
Hi, can you show me the the `tf` file, is that posible ?

**Comment by martynbristow** [comment]
The state is GitLab managed and it's normally run via CI...

**Comment by martynbristow** [comment]
Let me know if you need anything else to see into it

**Comment by martynbristow** [comment]
[civo2.zip](https://github.com/civo/terraform-provider-civo/files/10229366/civo2.zip)

I've reproduced the error with a new terraform project. I've

If there's something wrong in the terraform, it's not meaningfully failing. 

The failure happens on a Terraform Update. Create is unaffected.

## Method

- `terraform init`
- `terraform apply` -> Waiting til stable
- Change No Nodes in cluster 1-2 or 2-1... Forces Change
- `terraform apply`-> 🔥 with stack trace

**Comment by alejandrojnm** [comment]
Ok I will check this, tomorrow, will be my first task, thanks for the report
