### ISSUE TITLE
Failing to find k8s cluster after deletion

### ISSUE THREAD

**Issue by vCra** [civo/terraform-provider-civo#16]
After deleting a cluster outside of terraform, with the cluster still existing within the tfstate, the provider attempts to connect to the cluster, which no longer exists.

```
civo_kubernetes_cluster.cluster: Refreshing state... [id=<cluster guid>]

Error: [ERR] failed to find the kubernets cluster: unable to find <cluster guid>, zero matches
```

Terraform should recreate the cluster.
Current workaround is to rm the cluster from state before applying terraform

**Comment by alejandrojnm** [comment]
Hi @vCra, this error gives you when you run plan, refresh?

**Comment by vCra** [comment]
Yep - tried refresh, plan and apply
