### ISSUE TITLE
Issue Templates ⚠

### ISSUE THREAD

**Issue by ItsRoy69** [civo/terraform-provider-civo#163]
Issue Templates are awesome to have

Since there are alot of folks contributing to this Opensource project i would suggest we have `ISSUE TEMPLATES`
That way we can categorize the issues more and manage it more decently.
I can work on this if I am being assigned
![Screenshot 2023-01-21 200951](https://user-images.githubusercontent.com/78967360/213871897-05a066d2-7bf0-4287-bfa4-1ecde4120f07.png)

Here's how the forms looks :
![image](https://user-images.githubusercontent.com/78967360/213871944-17f5a981-5cf9-400e-baf1-f2d4c157e38e.png)

**Comment by Sindhuinti** [comment]
Hey @ItsRoy69 I would like to work on this issue.

**Comment by alejandrojnm** [comment]
Hi @ItsRoy69 thanks for the collaboration, send the PR and we can see.

**Comment by Sindhuinti** [comment]
Hey @alejandrojnm I have already worked on this issue. Here the PR #173. Please review this.
