### ISSUE TITLE
Cannot use provider with Terraform v0.13

### ISSUE THREAD

**Issue by jhole89** [civo/terraform-provider-civo#17]
This is more of a heads up/warning but I was playing around with the civo provider today and noticed that it is unusable since upgrading to Terraform version 0.13.0-beta1.

Despite having the provider locally as described in the docs (which previously worked fine), with the upgrade to v0.13 terraform now seems to ignore this and search the registry for the civo provider, where it is not currently available from.

Obviously terraform 0.13 is still in beta, but I thought it best to bring this to attention before 0.13 is released for general use.

![image](https://user-images.githubusercontent.com/19894385/84608465-77067d80-ae67-11ea-939d-1f3a7506f27c.png)

**Comment by alejandrojnm** [comment]
Hi @jhole89, yes you got that error because civo is not yet in the terraform registry, that is the reason you got that error. Ypu can follow this [guide](https://www.civo.com/learn/using-the-civo-terraform-provider) and try again.

**Comment by jhole89** [comment]
Hey @alejandrojnm, yeah I'm aware as I've been using it with tf 0.12 fine (you can see the terraform-civo-provider) in my tf plugins above. I was trying to explain that in tf 0.13 it seems to go around this and ignore locally installed providers and instead only search for providers that are listed in the registry (at least by default - I'm not sure if they've added a setting to revert this this behaviour).

**Comment by alejandrojnm** [comment]
i found a solution, @andyjeffries we need add civo to the registry of terraform. This is the link https://registry.terraform.io/sign-in, but i think i need finish all test first before send the request to HashiCorp
