### ISSUE TITLE
[BUG] Error when using the kubernetes_version flag

### ISSUE THREAD

**Issue by dcristobalhMad** [civo/terraform-provider-civo#186]
### Description

According to the documentation, with the latest version of the provider, an attempt has been made to update the cluster with the kubernetes_version flag and the latest k3s version. An error appears denying that this flag is operational in that version of the provider.

### Screenshots

![image](https://github.com/civo/terraform-provider-civo/assets/97036642/d82bb016-2472-460d-ae86-579bc5dd288b)
![image](https://github.com/civo/terraform-provider-civo/assets/97036642/719d9db4-986b-4c12-9d25-801b68e4f09c)

**Comment by fernando-villalba** [comment]
@uzaxirr check if this is still an issue after all the fixes we've done,   if not, close.

**Comment by uzaxirr** [comment]
This is fixed via: https://github.com/civo/terraform-provider-civo/pull/276
