### ISSUE TITLE
[BUG] Adding application to existing kubernetes cluster nothing happened

### ISSUE THREAD

**Issue by WillyRL** [civo/terraform-provider-civo#187]
### Description

Hi There,
I just create my first kubernetes cluster on CIVO using civo terraform provider, but when i'm tried to update the cluster to add the `civo-cluster-autoscaler` nothing happened after terraform apply

```
applications = "civo-cluster-autoscaler"
```
After asking the same question on Civo Community Slack, @zulh-civo ask me to create the issue here.

Thanks !

**Comment by fernando-villalba** [comment]
Duplicate of #258 We will be addressing this issue shortly. Thanks for reporting!
