### ISSUE TITLE
[BUG] resource civo_instance shows planned changes (in ssh key and script field) without any changes

### ISSUE THREAD

**Issue by rajatjindal** [civo/terraform-provider-civo#194]
### Description

i am trying to use the provider to setup some instances on Civo, and even without changing anything, the plan always try to change the ssh-key field on the resource.

on trying to understand what might be causing this, i think it is happening because [here](https://github.com/civo/terraform-provider-civo/blob/a19bdbf147bc1a4d0a929aadcb02b25bfb754cb6/civo/resource_instance.go#L340) we are using civogo.Instance.SSHKey instead of civogo.Instance.SSHKeyID

could you please take a look and provide your feedback if this report makes sense or I am missing something here. 

thank you.

**Comment by alejandrojnm** [comment]
OK I will check this

**Comment by fernando-villalba** [comment]
This should be fixed now. Report back if you still experiencing the same issue
