### ISSUE TITLE
[FEATURE] Allow "civo_network" to specify the nameserver and cidr

### ISSUE THREAD

**Issue by mrsimonemms** [civo/terraform-provider-civo#202]
### Description

The Civo CLI allows a network to be created with both `--cidr-v4` and `--nameservers-v4` specified. This doesn't appear to be possible with [Terrform](https://registry.terraform.io/providers/civo/civo/latest/docs/data-sources/network).

1. Am I missing something and is it already possible to do with Terraform?
2. If not, can we have some way of doing this with TF please?

**Comment by uzaxirr** [comment]
Hey,
from what i see is that CIDR and Nameserver is already been implemented in the network resource. 
https://github.com/civo/terraform-provider-civo/blob/master/civo/network/resource_network.go#L33

You can use the fields `cidr_v4` and `nameservers_v4` in your network block.
Let me know if this resolves your query.

**Comment by mrsimonemms** [comment]
Yes, you're right. It doesn't solve the problem of use in Terraform though - this feature was only done ~3 weeks ago, but the latest (`1.0.39`) release was done in October.

I guess a new release should solve that problem. Any idea when the next release is scheduled?

**Comment by mertcangokgoz** [comment]
I'm waiting for the new version to arrive. 👍🏻 especially this one

**Comment by mrsimonemms** [comment]
@uzaxirr what's the policy/release schedule? Anything I can do to help expedite this?

**Comment by mertcangokgoz** [comment]
Anything? @uzaxirr

**Comment by uzaxirr** [comment]
Here you go everyone: https://github.com/civo/terraform-provider-civo/releases/tag/v1.0.40

**Comment by uzaxirr** [comment]
Closing this issue wrt: #200
