### ISSUE TITLE
"New docs format" seems to move away from Terraform standard

### ISSUE THREAD

**Issue by stack72** [civo/terraform-provider-civo#21]
The Terraform standard for docs formatting is to use a website folder - this commit https://github.com/civo/terraform-provider-civo/commit/a3ee77767e97f43cc6659786d3ea137603f758cd moves the docs away from this standard

Was there any specific reason for this?

**Comment by alejandrojnm** [comment]
We don't have a documentation in the terraform.io site so we decide to move all to the new version, which is the registry https://www.terraform.io/docs/registry/providers/docs.html#migrating-legacy-providers-docs
