### ISSUE TITLE
Creating volumes on networks other than the default hangs indefinitely 

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#213]
## Issue

When creating a volume with terraform in a network that's not the default, it hangs forever, even though the volume gets successfully created.

Here is the code to reproduce the issue

```hcl
 resource "civo_network" "test-issue" {
     label = "test-issue"
 }


resource "civo_volume" "test-volume-issue" {
  name       = "test-volume-issue-volume"
  size_gb    = 1
  network_id = civo_network.test-issue.id
}
```

I have waited up to 20 minutes and it never ends. Using the default network it works fine.

(Tested on LON1 region, have not tested in other regions to see if the issue is the same everywhere)

## Acceptance criteria

* Ensure creating volumes works the same way on additional networks.

### Screenshots

<img width="720" alt="image" src="https://github.com/civo/terraform-provider-civo/assets/15110153/a13d1e9f-6b8b-4062-bd21-40c712f521e6">

**Comment by uzaxirr** [comment]
unable to replicate it, perhaps you might not be having any other resources in that network. You need to have atleast one (cluster, db, instanse etc) in that network

**Comment by uzaxirr** [comment]
unable to replicate it, perhaps you might not be having any other resources in that network. You need to have atleast one (cluster, db, instanse etc) in that network
