### ISSUE TITLE
return a descriptive error when api call fails

### ISSUE THREAD

**Issue by guitcastro** [civo/terraform-provider-civo#23]
Iam getting the following error:

`[ERROR] eval: *terraform.evalReadDataRefresh, err: Unable to load records: [ERR] error retrieving all templates: Unknow Error`

For this piece of code:

```
data "civo_template" "ubuntu" {
   filter {
        key = "code"
        values = ["ubuntu-18.04"]
   }
}
```

I got the same error for this other piece of code (note, the error above started to appear out of no where, the code usually fail in bellow step)
```
Error: [ERR] failed to create instance: Unknow Error

  on ../civo_ha/provider.tf line 57, in resource "civo_instance" "node_02":
  57: resource "civo_instance" "node_02" {
```

And last week I got the same error beacuse I was using a wrong token, this lead to almost impossible way to troubleshoot what´s is going on.

**Comment by guitcastro** [comment]
By the way, the error is because I didn´t have a credit card in CIVO

**Comment by alejandrojnm** [comment]
Hi @guitcastro i will check this

**Comment by alejandrojnm** [comment]
Hi @guitcastro with the last update you shouldn't see the `Unknown Error` anymore, let me know if happens again

**Comment by marshyon** [comment]
I'm getting it now

$ civo kubernetes ls
Error: UnknownError
