### ISSUE TITLE
Error: "public_ip": this field cannot be set

### ISSUE THREAD

**Issue by guitcastro** [civo/terraform-provider-civo#24]
It´s not possible to set the field `public_ip `in `civo_instance`  I believe that is because it´s being used as argument and attributes.

**Comment by alejandrojnm** [comment]
Hi @guitcastro let me check this

**Comment by alejandrojnm** [comment]
Hi the problem is the field is not `public_ip` is `public_ip_requiered` the `public_ip` is a computed field, the documentation is wrong i will fix now

**Comment by guitcastro** [comment]
@alejandrojnm Thanks!
