### ISSUE TITLE
[BUG] Terraform fails to create a new network after multiple attempts: timeout reached

### ISSUE THREAD

**Issue by albertomr86** [civo/terraform-provider-civo#242]
### Description

Unable to create a network using Terraform. However, it's possible via UI.

```hcl
terraform {
  required_providers {
    civo = {
      source  = "civo/civo"
    }
  }
}

provider "civo" {
  token  = "<token>"
  region = "NCY1"
}

resource "civo_network" "main" {
  region          = "NCY1"
  label           = "prod"
  cidr_v4         = "172.16.0.0/22"
  nameservers_v4  = ["8.8.8.8", "8.8.4.4", "1.1.1.1"]
}
```

### Screenshots

![Screenshot 2024-06-24 at 12 00 49 AM](https://github.com/civo/terraform-provider-civo/assets/4607250/9bf547b4-cc80-436f-b69d-d10beffe938c)

**Comment by uzaxirr** [comment]
hey @albertomr86 can you check if you already have a network in NYC1 with name "prod"

**Comment by uzaxirr** [comment]
Hey @albertomr86 
This is more likely a problem with your tf files rather than a bug in the provider. There seem to be a typo in "NYC1" in your code which is likely to cause the issue. You can refer to the below block
`NCY1` -> `NYC1`


```
resource "civo_network" "main" {
  region          = "NCY1"
  label           = "prod"
  cidr_v4         = "172.16.0.0/22"
  nameservers_v4  = ["8.8.8.8", "8.8.4.4", "1.1.1.1"]
}


```

**Comment by albertomr86** [comment]
Yep. Good catch. Consequences of late-night coding. Thanks, @uzaxirr 
It's working as expected.
