### ISSUE TITLE
[BUG] When creating a resource with a public ip address in a different region, quota increases without resources being created 

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#249]
## Issue

By accident I forgot to set the default region to LON1 (default was NYC1) while specifying the region of the instance to LON1 and this is what happened when I applied this code:

```hcl
resource "civo_reserved_ip" "www" {
    name = "test-ip" 
}


resource "civo_instance" "foo" {
    hostname = "amazingthingy20"
    tags = ["python", "nginx"]
    notes = "This is a test-issue"
    size = "g3.xsmall"
    region = "LON1"
    reserved_ipv4 = civo_reserved_ip.www.id
    firewall_id = "default-default"
    disk_image = "debian-10"
}

```

The following happens when applying the code above:

1. the reserved ip gets created
2. The civo instance resource does NOT get created
3. Instead it keeps trying to create the resource while the quota for CPU, Disk, public ip addresses, Volumes and instances keeps increasing. After cancelling the action takes some time until the quota clears.

Applying:

<img width="690" alt="image" src="https://github.com/civo/terraform-provider-civo/assets/15110153/d5a75072-a952-42ee-86eb-10f2109a4330">

If you go into the quota page as you do that and keep refreshing, you will see it progressively balloon until all is filled:

<img width="2136" alt="image" src="https://github.com/civo/terraform-provider-civo/assets/15110153/b02ed495-2004-4804-9333-cdbab1d3e2df">

## Acceptance Criteria

* Ensure that the operation fails if it tries to assign a public ip from a different region and  it doesn't create "ghost resources" in the background.

**Comment by Praveen005** [comment]
Hi @uzaxirr Can I work on this issue?

**Comment by uzaxirr** [comment]
Hey @Praveen005 can you outline your approach here.

**Comment by Praveen005** [comment]
@uzaxirr, Here's my assessment of the problem:

1. It first creates the `civo_reserved_ip` resource with the default region, `NYC1`
2. It then tries to create the instance resource with region `LON1`, if unsuccessful, retries.
3. The likely reason for resource ballooning is, each retry will make an API call for instance creation, and for each such retry, some ancillary resources quota gets reserved.

Now, I feel, to solve this issue, we should fail at the very first instance when there is a region mismatch(add checks in `resourceInstanceCreate()`) and don't retry.


While this may likely address the issue at hand, but I feel this ghost resource creation should be handled in a better way on the API side. 

I'd appreciate your input on this approach.

Thank you.

**Comment by Praveen005** [comment]
Hi @uzaxirr,

Whenever you have a moment, could you please review my approach?

Thank you!
Praveen

**Comment by Praveen005** [comment]
Hi @uzaxirr,

#275 fixes this issue it seems. 

I tried recreating it, but rightly got an error:

`main.tf`:

<img width="286" alt="Screenshot 2024-07-24 214353" src="https://github.com/user-attachments/assets/2797499e-fcae-4bdb-bf48-750f81f1f819">

Error correctly getting logged:

<img width="826" alt="Screenshot 2024-07-24 214054" src="https://github.com/user-attachments/assets/a2e228bc-fcd1-490d-b5a6-460dbeb746a2">

**Comment by uzaxirr** [comment]
closing wrt: https://github.com/civo/terraform-provider-civo/pull/275
