### ISSUE TITLE
DNS record type causes update in-place

### ISSUE THREAD

**Issue by javicv** [civo/terraform-provider-civo#25]
When using a resource *civo_dns_domain_record* to create a DNS record the type must be "A", but the terraform.tfstate stores this type as "a".

This difference causes an update in-place each time you try to apply anything.
![image](https://user-images.githubusercontent.com/18577298/98533254-03846300-2283-11eb-8d09-cb5727a5c622.png)

**Comment by alejandrojnm** [comment]
Thanks for this report, I will check now and sorry for the delay
