### ISSUE TITLE
[BUG] Changing cni in civo_kubernestes_cluster resource after creation does nothing

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#260]
## Issue

Changing `cni` after creation does nothing.

```hcl

provider "civo" {
  region = "LON1"
}




data "civo_size" "xsmall" {
    filter {
        key = "type"
        values = ["kubernetes"]
    }

    sort {
        key = "ram"
        direction = "asc"
    }
}

resource "civo_kubernetes_cluster" "my-cluster" {
    name = "my-cluster"
    applications = "mariadb:5GB"
    firewall_id = civo_firewall.my-firewall.id
    # cni = "cilium" # uncomment this after creation
    pools {
        label = "front-end" // Optional
        size = element(data.civo_size.xsmall.sizes, 0).name
        node_count = 2
    }
}
```

## Acceptance criteria

* Since we don't support changing the CNI of a running cluster. We should error out "Changing the CNI of a running cluster is not supported."

**Comment by Praveen005** [comment]
Hi @uzaxirr,

This issue can also be resolved by similar `HasChange` check for the `cni` attribute.

Here's the result:

<img width="447" alt="Screenshot 2024-07-18 220301" src="https://github.com/user-attachments/assets/1b58d602-2993-4928-8b32-0ccb9fcefcfd">


Would it be okay if I take this up?
