### ISSUE TITLE
[BUG] We need to support changing the firewall_id of a cluster

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#262]
## Issue

Currently when you try to change the `firewall_id` of a cluster you get an error:

<img width="718" alt="image" src="https://github.com/user-attachments/assets/97a427d8-c091-4d01-a645-cdd7ffea2efd">

However updating the `firewall_id` of a cluster is supported by the API, hence we should allow users to do so with terraform

Sample code:

```hcl

provider "civo" {
  region = "LON1"
}

resource "civo_firewall" "my-firewall" {
    name = "my-firewall"
}


data "civo_size" "xsmall" {
    filter {
        key = "type"
        values = ["kubernetes"]
    }

    sort {
        key = "ram"
        direction = "asc"
    }
}

resource "civo_kubernetes_cluster" "my-cluster" {
    name = "my-cluster"
    applications = "mariadb:5GB"
    firewall_id = civo_firewall.my-firewall.id # change this
    # cni = "cilium"
    # network_id = civo_network.test-issue.id
    pools {
        label = "front-end" // Optional
        size = element(data.civo_size.xsmall.sizes, 0).name
        node_count = 2
    }
}
```

## Acceptance criteria

* Enable updating clusters `firewall_id` in terraform

**Comment by Praveen005** [comment]
Hi @uzaxirr 

I tried solving his issue. If you allow, I would like to share my thoughts.

**Comment by uzaxirr** [comment]
@Praveen005 sure go ahead

**Comment by Praveen005** [comment]
While the API does allow us to change the `firewall_id` post creation, but here we have a problem, 

In the `KubernetesClusterConfig{}` we don't have any `FirewallID` field. And this can be solved if we update our dependency which uses `v0.3.70` of the `civogo` client.

https://github.com/civo/terraform-provider-civo/blob/4cc441cbf769b30ae4a2e91817f2f1c4f0cf86a8/go.mod#L4

Because this was recently added in `civogo`.

<img width="932" alt="Screenshot 2024-07-23 172113" src="https://github.com/user-attachments/assets/a6be7b7c-93d0-4a88-8e79-6bc1c4b2e69d">


Once we do it, we'll have to update the config. as follows and I believe it would work.
```
config.FirewallID = d.Get("firewall_id").(string)
config.Region = apiClient.Region
````

**Comment by uzaxirr** [comment]
> While the API does allow us to change the `firewall_id` post creation, but here we have a problem,
> 
> In the `KubernetesClusterConfig{}` we don't have any `FirewallID` field. And this can be solved if we update our dependency which uses `v0.3.70` of the `civogo` client.
> 
> https://github.com/civo/terraform-provider-civo/blob/4cc441cbf769b30ae4a2e91817f2f1c4f0cf86a8/go.mod#L4
> 
> Because this was recently added in `civogo`.
> 
> <img alt="Screenshot 2024-07-23 172113" width="932" src="https://private-user-images.githubusercontent.com/42026111/351312499-a6be7b7c-93d0-4a88-8e79-6bc1c4b2e69d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MzU5MTQsIm5iZiI6MTcyMTczNTYxNCwicGF0aCI6Ii80MjAyNjExMS8zNTEzMTI0OTktYTZiZTdiN2MtOTNkMC00YTg4LThlNzktNmJjMWM0YjJlNjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDExNTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzMDRlZTUwMGNkMWViMDljZDEzYmQyN2M5NzNkYzZjZWQ3OTY3OTIxZmExZGM1OTU4MDRhMGY3YTE3NTQzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lvCh5NIFdISNkC2HaAcMPSx3AqIekzd8FHZG6WrjVJs">
> Once we do it, we'll have to update the config. as follows and I believe it would work.
> 
> ```
> config.FirewallID = d.Get("firewall_id").(string)
> config.Region = apiClient.Region
> ```

Yeah you are correct you need to upgrade SDK version. Go ahead and raise a PR
