### ISSUE TITLE
[BUG] Instance resource field `disk_image` marked as optional but you get error when omiting

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#283]
## Description

[BUG] Instance resource field `disk_image` marked as optional but you get error when omiting

![image](https://github.com/user-attachments/assets/9e7d812b-537b-47d7-9fa5-4142776df81d)

## Acceptance Criteria

* Make it so it's optional and defaults to the same as the CLI/Dashboard.

**Comment by uzaxirr** [comment]
Resolved via: https://github.com/civo/terraform-provider-civo/pull/295
