### ISSUE TITLE
[BUG] Creating clusters with applications that have plans with spaces doesn't work

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#284]
## Issue

If you use the following command to create a cluster:

```
civo kubernetes create --applications "argocd,linkerd:Linkerd with Dashboard & Jaeger"
```

It works:

<img width="990" alt="image" src="https://github.com/user-attachments/assets/6a58c3a7-6ca6-4425-a32d-276c89d780f8">

However doing the same with Terraform doesn't:

```hcl

provider "civo" {

  region = "LON1"
}

resource "civo_firewall" "example" {
    name = "example-firewall"
    create_default_rules = true
    network_id = civo_network.example.id

}

resource "civo_network" "example" {
  label = "example-network8"

}


resource "civo_kubernetes_cluster" "example" {
    name = "example-cluster"
    applications = "argocd,linkerd:Linkerd with Dashboard & Jaeger" # Doesn't work
    network_id = civo_network.example.id
    firewall_id = civo_firewall.example.id

    cluster_type = "k3s"
    pools {
        label = "shop"
        size = "g4s.kube.small"
        node_count = 3
    }
}

```

Error:

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/1394c965-85e3-4fc4-8485-bbb4ad07e9a2">

Looks like the provider is stripping the spaces.

## Acceptance criteria

* Ensure it works the same way it does on the CLI

**Comment by Praveen005** [comment]
Hi @uzaxirr 

In here, 
Spaces are being trimmed from the `plans`'s name. 

correcting that fixes the issue. I believe this is how the API expects.

https://github.com/civo/terraform-provider-civo/blob/c9b61643378f97130d56aae00999e68168192bcd/civo/kubernetes/resource_kubernetes_cluster.go#L244

<img width="534" alt="Screenshot 2024-07-26 134935" src="https://github.com/user-attachments/assets/5e5ea3dc-1da7-4e0a-a0e0-2c7c87f3fad8">

Result:

<img width="466" alt="Screenshot 2024-07-26 135049" src="https://github.com/user-attachments/assets/aa39ec18-bcad-4021-93e3-6353aacc9d7d">

<img width="358" alt="Screenshot 2024-07-26 135137" src="https://github.com/user-attachments/assets/a102960e-bb63-4662-bcdc-df92d8506600">


<img width="783" alt="Screenshot 2024-07-26 135359" src="https://github.com/user-attachments/assets/1b4048d5-6bf8-485e-863c-2ae804aded97">

**Comment by uzaxirr** [comment]
> Hi @uzaxirr
> 
> In here, Spaces are being trimmed from the `plans`'s name.
> 
> correcting that fixes the issue. I believe this is how the API expects.
> 
> https://github.com/civo/terraform-provider-civo/blob/c9b61643378f97130d56aae00999e68168192bcd/civo/kubernetes/resource_kubernetes_cluster.go#L244
> 
> <img alt="Screenshot 2024-07-26 134935" width="534" src="https://private-user-images.githubusercontent.com/42026111/352452031-5e5ea3dc-1da7-4e0a-a0e0-2c7c87f3fad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzYzNzEsIm5iZiI6MTcyMjA3NjA3MSwicGF0aCI6Ii80MjAyNjExMS8zNTI0NTIwMzEtNWU1ZWEzZGMtMWRhNy00ZTBhLWEwZTAtMmM3Yzg3ZjNmYWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEwMjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZTRmNTc3MjFkNmE2MmFhNWE3YmM5MzQ1YWI5MjVkNzQ3MTE4OTlmZjg3ZDUyYTY1YmEzYTcyNzE3ODVkODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wVaNvMNlu-U1_HCnX8D3y9cqTU-lV7ftBPIr4S5LePQ">
> Result:
> 
> <img alt="Screenshot 2024-07-26 135049" width="466" src="https://private-user-images.githubusercontent.com/42026111/352452653-aa39ec18-bcad-4021-93e3-6353aacc9d7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzYzNzEsIm5iZiI6MTcyMjA3NjA3MSwicGF0aCI6Ii80MjAyNjExMS8zNTI0NTI2NTMtYWEzOWVjMTgtYmNhZC00MDIxLTkzZTMtNjM1M2FhY2M5ZDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEwMjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOWI5ZDYwYTFjYzAwMTViYzljNTVkNjQ2MjQ4MGYyZmRmYTYzNDJjNzM0ODZjZDY1NzRkZGJiMmM1ODc3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zuA5VFn5NNxUFpsFwtIL91udXmAOpDYRbW89eoPjHfk"> <img alt="Screenshot 2024-07-26 135137" width="358" src="https://private-user-images.githubusercontent.com/42026111/352452687-a102960e-bb63-4662-bcdc-df92d8506600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzYzNzEsIm5iZiI6MTcyMjA3NjA3MSwicGF0aCI6Ii80MjAyNjExMS8zNTI0NTI2ODctYTEwMjk2MGUtYmI2My00NjYyLWJjZGMtZGY5MmQ4NTA2NjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEwMjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNzdmNTQxODE5YTg5OWVhNzdlYjIzY2YxYjYzMDAwYWY2NDhkYTg3Mzk0MmZjNmEyMmFkNWIzNjk0MzhjYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-pgyYGZeJoiZtnNTAMbPZhwE90Kn1v_eN9NO29hd84"> <img alt="Screenshot 2024-07-26 135359" width="783" src="https://private-user-images.githubusercontent.com/42026111/352453336-1b4048d5-6bf8-485e-863c-2ae804aded97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzYzNzEsIm5iZiI6MTcyMjA3NjA3MSwicGF0aCI6Ii80MjAyNjExMS8zNTI0NTMzMzYtMWI0MDQ4ZDUtNmJmOC00ODVlLTg2M2MtMmFlODA0YWRlZDk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDEwMjc1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZGVjMmVhZTU2ZjZiNWRlMjA0NThkYjk4OTc4NDc0YjhkY2EzZDIzMzA3NGVmMjQ3OTU2ZWRlMzFjYWY0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qR-qTWGJZC7fOTQq_wApgBAyv6ZS1e3whtpb-zYOUQ">

@Praveen005 Please raise a PR
