### ISSUE TITLE
[FEATURE] When creating a Civo instance the user should be able to decide whether to write inital_password to state

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#297]
## Description

When creating a civo_instance resource the initial password gets saved to state, this allows a user to access the machine with elevated privileges 

I can see many scenarios (perhaps most?) where a user may not want that at all. Users may want to just create an instance and then fetch the configuration with the Civo CLI or Dashboard, etc.

## Acceptance Criteria

* Create a new boolean configuration input called `write_password` or something like that. When `true` write initial password to state, when `false` don't write it.
* Ideally it would be good to default this to false, but it may cause backward compatibility issues. I say we default it to false, but output a message to the user saying that if they want to keep it to add the `write_password` flag and set it to `true`. For example:

`"Starting on version x the initial password is not written to state by default, if you wish to keep the initial password configuration in state, please add the input write_password and set it to true"`

**Comment by Praveen005** [comment]
Hi @uzaxirr 

I worked on this issue and would like to explain my approach for your review.

The approach is similar to that I followed for issue 296, Here too I added a boolean attribute `write_password` in resource schema, like below:

<img width="461" alt="Screenshot 2024-08-07 172255" src="https://github.com/user-attachments/assets/4010ad84-52ec-46ec-bbfe-ee4a478e234b">

In `resourceInstanceRead` I added a check which sets the value of `initial_password` to an empty string if `write_password`'s value is `false`

<img width="340" alt="Screenshot 2024-08-07 172315" src="https://github.com/user-attachments/assets/278c73f5-b836-4b6c-ad77-e79a82e77ce7">

There's also a validation function `ValidateProviderVersion` which throws a warning if the provider version used by user is `<=1.0.49`.

------------------------------------------------------------

Post above changes, the resource creation/update goes through as intended and as required in this issue.

`main.tf`:

<img width="424" alt="Screenshot 2024-08-07 165718" src="https://github.com/user-attachments/assets/eb9b8135-715c-4acf-8fa6-8780e5a19929">

Showing the warning correctly:

<img width="722" alt="Screenshot 2024-08-07 165606" src="https://github.com/user-attachments/assets/4a62d235-6bdf-4b9b-b531-83b90430621d">

`initial_password` being correctly written to the terraform state:

<img width="774" alt="Screenshot 2024-08-07 165644" src="https://github.com/user-attachments/assets/0ed8ac91-1e58-4330-aeff-008934f5623d">

------------------------------------------
Updated the configuration:

<img width="431" alt="Screenshot 2024-08-07 173715" src="https://github.com/user-attachments/assets/6f1c7a2a-acdc-4143-ae42-ab0ce00d9e44">

correctly hiding the `initial_password`:

<img width="774" alt="Screenshot 2024-08-07 170001" src="https://github.com/user-attachments/assets/45ff3d12-4a31-465f-afe0-2c648aeb8ade">

----------------------------------------------------------------------

When `write_password` is not specified in `main.tf`, it correctly defaults to `false`:

<img width="426" alt="Screenshot 2024-08-07 174607" src="https://github.com/user-attachments/assets/414d2e39-56eb-436d-a51f-a75b35150460">

correctly defaulting to `false`:

<img width="259" alt="Screenshot 2024-08-07 174417" src="https://github.com/user-attachments/assets/600dd29f-ef26-44d3-b124-d0ab04ef843a">

Resource creation successful:

<img width="349" alt="Screenshot 2024-08-07 174231" src="https://github.com/user-attachments/assets/37203cd7-5a91-4c54-8145-afee9f7fedb0">

correctly hiding the `initial_password`:

<img width="356" alt="Screenshot 2024-08-07 174313" src="https://github.com/user-attachments/assets/acbb7c0a-d12f-4735-b2fe-ddcd187b6d32">

**Comment by uzaxirr** [comment]
@Praveen005 this looks good please raise a PR
