### ISSUE TITLE
Unable to create kubernetes cluster

### ISSUE THREAD

**Issue by ulm0** [civo/terraform-provider-civo#31]
When trying to create a cluster i get the following error:

```sh
Error: [ERR] failed to create the kubernets cluster: DatabaseServiceNotFoundError: Failed to find the size within the internal database
```

**Comment by alejandrojnm** [comment]
Yes i'm woking in the new provider

**Comment by akosveres** [comment]
Not to rush anyone, but any updates on this @alejandrojnm? Or maybe we can help with a PR if it's a small thing?

**Comment by akosveres** [comment]
My workaround for this was to create the k3s cluster manually (I did it in the console but can be done through the CLI) and then I imported it into terraform via the `terraform import` command.

**Comment by alejandrojnm** [comment]
Hi nice, i was stuck in the launch of Civo, but I'm back to trail, i got some problem with the migration to Terraform v2 SDK but i already fixed it
