### ISSUE TITLE
[BUG] When user specifies ingress rules for the firewall, create_default_rules should not be allowed

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#311]
### Description

If the users specify their own firewall rules, `create_default_rules` should not be allowed for two reasons:

```terraform
resource "civo_firewall" "example" {
  name                 = "example-firewall"
  network_id           = civo_network.example.id
  create_default_rules = true
  ingress_rule {
    label      = "http"
    protocol   = "tcp"
    port_range = "80"
    cidr       = ["0.0.0.0"]
    action     = "allow"
  }
}

```

1. The user has no visibility of the default rules in terraform
2. It creates issues when adding and removing that field after adding it. For example, when you add the `create_default_rules = true` afterwards it tries to destroy the firewall and recreate it:

<img width="2075" alt="image" src="https://github.com/user-attachments/assets/21f5229e-a9c9-43cd-ad49-a70be16053af">

### Acceptance Criteria

* Do not allow `create_default_rules` set to `true` when users specify their own rules. 
* Perhaps the default should be false

**Comment by Praveen005** [comment]
Hi @uzaxirr 

For this issue, should we error out?

<img width="669" alt="Screenshot 2024-08-09 123114" src="https://github.com/user-attachments/assets/5a68b1b7-0c5b-4529-ba8c-c94e30de74b1">

or silently set the value of `create_default_rules` to `false`, like below?

<img width="651" alt="Screenshot 2024-08-09 123335" src="https://github.com/user-attachments/assets/471060ca-f545-4fca-8874-e8cce63e3a54">


-------------------------------------------------

> Perhaps the default should be false

Does this acceptance criteria require us to set the `default` attribute below to `false`? would this be prudent to do so, after adding the above checks?

<img width="667" alt="Screenshot 2024-08-09 123523" src="https://github.com/user-attachments/assets/4f1fbf5c-54da-448a-8d1e-a479b68696e9">

**Comment by uzaxirr** [comment]
@Praveen005 
if any of the `ingress_rule` or `egress_rule` is specified and `create_default_rules` is set to `true` then we should error out saying that `"create_default_rules can't be true when ingress_rule or egress_rule is specified"` in the terraform plan phase itself.
