### ISSUE TITLE
[BUG] When using tilde ~ on credentials_file it does not expand to home directory

### ISSUE THREAD

**Issue by fernando-villalba** [civo/terraform-provider-civo#317]
### Description

Using tilde for the home directory in the configuration for credentials_file does not work:

```terraform
provider "civo" {
  region = "LON1"
  credentials_file = "~/token"
}
```

This is because `os.ReadFile(path)` [does not expand](https://stackoverflow.com/questions/62482482/how-to-read-file-path-containing-tilde) the tilde.

#### Proposed solution

We can use the [go-homedir function ](https://github.com/mitchellh/go-homedir) here is an [example](https://github.com/hashicorp/terraform/blob/1d770d605e5071a80ee51bc23312e7542e3976b7/internal/lang/funcs/filesystem.go#L155)

Any other solution with minimal code required would do, there is a built-in function called os/user but according to Mitchell Hashimoto, the create of the go-homedir function above:

_Why not just use os/user? The built-in os/user package requires cgo on Darwin systems. This means that any Go code that uses that package cannot cross compile. But 99% of the time the use for os/user is just to retrieve the home directory, which we can do for the current user without cgo. This library does that, enabling cross-compilation._

Or that was the case 6 years ago, it may be different today, haven't done the research.

### Acceptance Criteria

* Ensure that the tilde (~) gets expanded properly. Don't use too much code for this.

**Comment by uzaxirr** [comment]
Resolved via: https://github.com/civo/terraform-provider-civo/pull/322
