### ISSUE TITLE
[DOCS] kubernetes latest stable version

### ISSUE THREAD

**Issue by NerdyShawn** [civo/terraform-provider-civo#319]
### Description

For specifying kubernetes version the document mentions the "latest available" which isn't exactly true given newer k8s versions in civo provider are available, but haven't reached maturity of "stable". The idea is to add the additional verbiage to reflect the reality that it is the "**latest stable available**" in a given cluster type.

### Acceptance Criteria

I can draft the PR but essentially just some more verbiage in place clearing up what the default behavior of kubernetes_version looks like.
- **latest stable available**

**Comment by NerdyShawn** [comment]
Proposed fix available via 
- #320

**Comment by fernando-villalba** [comment]
Good catch and thank you for the contribution @NerdyShawn !
