### ISSUE TITLE
[BUG] DatabaseNetworkExistsError network resources seemingly orphaned post destroy

### ISSUE THREAD

**Issue by NerdyShawn** [civo/terraform-provider-civo#324]
### Description

1. **civo_network** resources seem to have issues cleaning up in my account
2. Start with a simple network resource it will create, but if you destroy and try to re-create it will complain that it already exists in spite of being gone from the cli & ui.
```c
resource "civo_network" "custom_net" {
    label = "custom_net"
}
```
the error that occurs when you try to apply after a successful destroy
```c
civo_network.custom_net: Creating...
╷
│ Error: [ERR] failed to create network: DatabaseNetworkExistsError: A network with this name already exists, please choose another
│ 
│   with civo_network.custom_net,
│   on main.tf line 37, in resource "civo_network" "custom_net":
│   37: resource "civo_network" "custom_net" {
│ 
╵
``
verifying in cli & ui and all regions that I only am using two networks
```c
civo network ls
+--------------------------------------+-----------------------+--------+---------+--------+
| ID                                   | Label                 | Region | Default | Status |
+--------------------------------------+-----------------------+--------+---------+--------+
| b4347154-5b62-4c55-9e47-b2c664f05e07 | custom_network_potato | NYC1   | false   | Active |
+--------------------------------------+-----------------------+--------+---------+--------+
| cce84526-cda8-4d09-bcff-e4d5e1fe6483 | Default               | NYC1   | true    | Active |
+--------------------------------------+-----------------------+--------+---------+--------+
```

3. as a workaround I've just been creating new network names after I destroy resources for the day, then come back tomorrow. Now I'm about to exhaust my network quotas that are from what I can tell are seemingly orphaned, yet present in a database backend still that I can't see.
```c
civo quota ls | grep Network
          Network Count : 9/10
```

### Acceptance Criteria

Although the destroy works correctly, it appears that it somehow still exists in a database backened as it still is being marked against the quota. Investigate quota and what the network resource doesn't fully leave post destroy for my account.

**Comment by NerdyShawn** [comment]
I've also engaged support on this as I suspect it might be more of an issue with my account versus the terraform provider.

**Comment by uzaxirr** [comment]
We are actively debugging this issue. Will surely update you.

**Comment by fernando-villalba** [comment]
@NerdyShawn It's an internal issue, not terraform provider related but glad you brought it up so we can raise even more awareness of it internally and perhaps give it more priority. I am going to be closing this issue now, but just letting you know it's not forgotten, I have raised tickets internally and made a reference to this.
