### ISSUE TITLE
Changing node size not applied

### ISSUE THREAD

**Issue by Waterdrips** [civo/terraform-provider-civo#33]
I created a cluster with g3.xsmall nodes, then updated the size to g3.small which provided the following output

```hcl
Terraform will perform the following actions:

  # civo_kubernetes_cluster.this will be updated in-place
  ~ resource "civo_kubernetes_cluster" "this" {
        id                     = "19dccf7e-2cb3-40da-a207-bba1654f6f26"
        name                   = "openfaas-cluster"
      ~ target_nodes_size      = "g3.xsmall" -> "g3.small"
        # (15 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

civo_kubernetes_cluster.this: Modifying... [id=19dccf7e-2cb3-40da-a207-bba1654f6f26]
civo_kubernetes_cluster.this: Modifications complete after 5s [id=19dccf7e-2cb3-40da-a207-bba1654f6f26]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

It says its going to update in place, bit in the UI i still see a node pool with 3x g3.xsmall nodes and no additional node groups or indication that it did anything.

![image](https://user-images.githubusercontent.com/40488132/117936064-50adc400-b2fc-11eb-9228-b43766a0db9c.png)

**Comment by Waterdrips** [comment]
Actually, re-running the apply gives the same change every time, so its failing to make the update and always planning that change

**Comment by alejandrojnm** [comment]
Hi @Waterdrips we are working to fix this, thanks or the issue

**Comment by zulh-civo** [comment]
@Waterdrips - I'm sorry to inform that we do not yet support in-place upgrade for the Kubernetes node pool. We can't simply "delete" the old node pool and "create" a new node pool (with the new nodes size) because it will affect the running workloads in customer's cluster. Until we figure it out, the workaround is you need to create a new node pool with the new nodes size (`g3.small`).
