### ISSUE TITLE
[BUG] kubeconfig is not present in the output

### ISSUE THREAD

**Issue by jadolg** [civo/terraform-provider-civo#342]
### Description

When creating a new cluster, no kubeconfig data is saved in the output.
Provider version: "1.1.2"

### Acceptance Criteria

`civo_kubernetes_cluster` correctly fills the kubeconfig output

**Comment by Praveen005** [comment]
Hi @jadolg,

Starting from version `v1.1.0`, the `kubeconfig` data is no longer saved to the Terraform state by default. To enable this, you need to use the `write_kubeconfig` attribute and set it to true.

Please update your configuration accordingly. You can find more details in the [official documentation](https://registry.terraform.io/providers/civo/civo/latest/docs/resources/kubernetes_cluster#:~:text=write_kubeconfig%20(Boolean)%20(false%20by%20default)%20when%20set%20to%20true%2C%20kubeconfig%20is%20saved%20to%20the%20terraform%20state%20file).

Let me know if this resolves the issue!

Best,
Praveen

**Comment by jadolg** [comment]
Great! That solves my issue. Thank you very much. 
You might want to update the example found here https://registry.terraform.io/providers/civo/civo/latest/docs/resources/kubernetes_cluster though.
I found the new setting at the bottom of the file but the example showing how to get the kubeconfig file does not have it.

**Comment by Praveen005** [comment]
Hi @jadolg

I'm glad your issue got resolved. We'll make the necessary changes in the documentation. Thank you for the feedback.

Regards,
Praveen
