### ISSUE TITLE
[FEATURE] Bring back the `civo_token` setting in the provider

### ISSUE THREAD

**Issue by jadolg** [civo/terraform-provider-civo#343]
### Description

There are safe ways to use this setting. Loading the credentials from a SOPS encrypted file for instance (see [here](https://github.com/jadolg/civo-cluster/blob/14bb1c007960336f81e41e1ff7a568dfb6860823/main.tf#L3)). Removing it makes it less safe and convenient.

### Acceptance Criteria

The `civo_token` setting is added back to the provider.

**Comment by fernando-villalba** [comment]
Hi @jadolg, you can still use it but it is deprecated.

We will consider undeprecating it so it's still an option. The thing is, even using SOPS (correct me if I am wrong), the token would still be saved to state unencrypted, and we don't recommend having secret values in state if it can be avoided.

**Comment by jadolg** [comment]
I was not able to use it. It errors instead of throwing a warning. As for the security implications, my state is usually saved in a secure location. Besides that, OpenTofu has now the capability to encrypt the state https://opentofu.org/docs/language/state/encryption/. In any case, I think these considerations should be offloaded to the user instead of forcing them in the provider. Eg: A warning message telling me the token is saved unencrypted in the state instead of taking the option away.

**Comment by uzaxirr** [comment]
> I was not able to use it. It errors instead of throwing a warning. As for the security implications, my state is usually saved in a secure location. Besides that, OpenTofu has now the capability to encrypt the state https://opentofu.org/docs/language/state/encryption/. In any case, I think these considerations should be offloaded to the user instead of forcing them in the provider. Eg: A warning message telling me the token is saved unencrypted in the state instead of taking the option away.

Can you share the error that you are getting. It works fine for me.
<img width="649" alt="Screenshot 2024-09-06 at 3 45 54 PM" src="https://github.com/user-attachments/assets/801ffe61-ff1a-4694-b5e5-6316436d8c95">


Below is my provider definition

```
terraform {
  required_providers {
    civo = {
      source  = "civo/civo"
    }
  }
}
provider "civo" {
  region = "LON1"
  token = "YOUR_CIVO_API_KEY"
}

```

**Comment by jadolg** [comment]
Oh it actually worked this time! My bad. Looks like I was missing the actual error and blaming the warning for the problem. Thank you very much!

**Comment by fernando-villalba** [comment]
Thanks @jadolg we have taken your feedback onboard and we will undeprecate this in the future and provide and a warning in the documentation/and or error message.
