### ISSUE TITLE
[FEATURE] volumetype support 

### ISSUE THREAD

**Issue by alessandroargentieri** [civo/terraform-provider-civo#349]
### Description

Some regions are flagged with the custom_storage_class: true:
```
$ curl -H "Authorization: Bearer `mycivoapikey`" https://api.civo.com/v2/regions | jq
[
  {
       "code": "<regionCode>",
       "name": "<regionName>",
       ...
      "features": {
            ... 
            "custom_storage_class": true
       },
  },
```
For these regions we would be able to list all the volumetypes:
```
GET /v2/volumetypes
Response:
[
   {
     "name": "ms-xfs-2-replicas"
     "description": "<OPTIONAL>",
     "flags": ["foo", "bar"] // OPTIONAL
   },
   {
      "name": "ms-xfs-3-replicas"
      "description": "<OPTIONAL>",
      "flags": ["foo", "bar"] // OPTIONAL
    },
]
```
And let the user can select a volumetype.name and pass it to the following:
```
# create instance request
POST /v2/instances -d {... "volume_type": "<VOLUMETYPENAME_HERE>"}
# create volume request
POST /v2/volumes -d {... "volume_type": "<VOLUMETYPENAME_HERE>"}
```

### Acceptance Criteria

- be able to list the volumetypes if enabled
- be able to add the volumetype in the create instance request 
- be able to add the volumetype in the create volume request 
- be able to get the volumetype in output in the LIST/GET volumes/instances when it's present

**Comment by uzaxirr** [comment]
Added via: https://github.com/civo/terraform-provider-civo/pull/350
