### ISSUE TITLE
Firewall Issues - [ERR] failed to create a new firewall: UnknownError

### ISSUE THREAD

**Issue by lluked** [civo/terraform-provider-civo#41]
On running Terraform apply I am running into the following error:

```
╷
│ Error: [ERR] failed to create a new firewall: UnknownError
│ 
│   with civo_firewall_rule.https,
│   on vpc.tf line 35, in resource "civo_firewall_rule" "https":
│   35: resource "civo_firewall_rule" "https" {
│ 
╵
```

Config:

```
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    civo = {
      source = "civo/civo"
      version = "0.10.4"
    }
  }
}

provider "civo" {
  region = var.civo_region
}

resource "civo_network" "test" {
    label = "Test-Project"
}

resource "civo_firewall" "test" {
  name = "Test-Project"
  network_id = civo_network.test.id
}

resource "civo_firewall_rule" "http" {
  firewall_id = civo_firewall.test.id
  protocol = "tcp"
  start_port = "80"
  # end_port = "80"
  cidr = ["0.0.0.0/0"]
  direction = "ingress"
  label = "HTTP Ingress"
  depends_on = [civo_firewall.test]
}

resource "civo_firewall_rule" "https" {
  firewall_id = civo_firewall.test.id
  protocol = "tcp"
  start_port = "443"
  # end_port = "443"
  cidr = ["0.0.0.0/0"]
  direction = "ingress"
  label = "HTTPS Ingress"
  depends_on = [civo_firewall.test]
}
```

It appears the first rule applies fine however the second doesn't, I don't see anything obviously wrong with the config and if I take the first rule out the second works. It seems only one rule is able to be applied at a time. Also I tried with both end port defined and commented out.

Thanks,
Luke

**Comment by lluked** [comment]
Changing depends_on = [civo_firewall.test] to depends_on = [civo_firewall_rule.http] on the second rule results in a deployment with no issues, looks like a resourcing issue where both rules are attempted to be created at the same time. I couldn't find any documentation mentioning it was necessary to chain the firewall rules in order to deploy.

**Comment by alejandrojnm** [comment]
I'm checking this

**Comment by alejandrojnm** [comment]
This is already fixed, now the provider shows the error, but we need to check our endpoint to see what is happening.
