### ISSUE TITLE
instances terraform creation -  inconstitent state

### ISSUE THREAD

**Issue by jbdevopscz** [civo/terraform-provider-civo#43]
After succesfull "terraform apply" command coressponding instances are created. But after running "terraform apply" again - it will still wants to update something.   

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # civo_instance.funnel1 will be updated in-place
  ~ resource "civo_instance" "funnel1" {
        id                 = "ca39e1b2-9c95-4215-bb17-994b171cb904"
        tags               = []
      + template           = "a4204155-a876-43fa-b4d6-ea2af8774560"
        # (17 unchanged attributes hidden)
    }

  # civo_instance.funnel2 will be updated in-place
  ~ resource "civo_instance" "funnel2" {
        id                 = "3eaea460-4781-4e07-a05e-d731a74246a1"
        tags               = []
      + template           = "a4204155-a876-43fa-b4d6-ea2af8774560"
        # (17 unchanged attributes hidden)
    }

```
Plan: 0 to add, 2 to change, 0 to destroy.

**Comment by alejandrojnm** [comment]
Hi @jbdevopscz thanks for report this, can you share you config, the terraform version, the provider version in that way we can try to reproduce this error

**Comment by jbdevopscz** [comment]
> Hi @jbdevopscz thanks for report this, can you share you config, the terraform version, the provider version in that way we can try to reproduce this error

you can use just the template as example on the web, i am using terraform version 0.12.12 but also the last version.  The provider version is 0.10.4. - 6

**Comment by jbdevopscz** [comment]
also, if you not specify your own firewall (so the Default is used) the next terraform apply still aplying update in firewall_id

` ~ update in-place

Terraform will perform the following actions:

  # civo_instance.funnel1 will be updated in-place
  ~ resource "civo_instance" "funnel1" {
      - firewall_id        = "f5915384-63a8-4c54-9fa1-5c11a5c4d400" -> null
        id                 = "ff70c51d-7c62-42f9-9296-ff36215cc563"
        tags               = []
      + template           = "a4204155-a876-43fa-b4d6-ea2af8774560"
        # (16 unchanged attributes hidden)
    }

  # civo_instance.funnel2 will be updated in-place
  ~ resource "civo_instance" "funnel2" {
      - firewall_id        = "f5915384-63a8-4c54-9fa1-5c11a5c4d400" -> null
        id                 = "f150603c-00a4-4396-8bb0-56964500f8e7"
        tags               = []
      + template           = "a4204155-a876-43fa-b4d6-ea2af8774560"
        # (16 unchanged attributes hidden)
    }
`

**Comment by alejandrojnm** [comment]
Ta i will check this in the night
