### ISSUE TITLE
Show available node sizes in documentation

### ISSUE THREAD

**Issue by dirsigler** [civo/terraform-provider-civo#46]
The documentation doesn't show any hints on the available node sizes for a Kubernetes Cluster.
You can find a reference to a Data Source in the [Example Usage for the civo_kubernetes_cluster](https://registry.terraform.io/providers/civo/civo/latest/docs/resources/kubernetes_cluster#example-usage), but that one is a bit misleading, because the Data Source is not configured in the example.

Furthermore if you then check out the Data Source, you still have to get to know a fitting value to match against or fiddle around with Terraform to get the information.

I think it is better to add a table to the documentation or to link a external source with information about the current sizes, so people can easily start with creating cluster 🚀 

---

Currently a way to check sizes is either via https://www.civo.com/api/sizes#listing-available-sizes
or with following Data Source in Terraform:

```hcl
data "civo_instances_size" "test" {
    filter {
        key = "name"
        values = [""]
        match_by = "re"
    }
}

output "sizes" {
  value = data.civo_instances_size.test.sizes
}
```

EDIT:
The sizes can also be shown via Civo CLI, but Civo CLI should not be a requirement to have a quick working Terraform setup:

```sh

civo kubernetes size
+----------------+-------------+------------+-----+-------+-----+------------+
| Name           | Description | Type       | CPU | RAM   | SSD | Selectable |
+----------------+-------------+------------+-----+-------+-----+------------+
| g3.k3s.xsmall  | Extra Small | Kubernetes |   1 |  1024 |  15 | Yes        |
| g3.k3s.small   | Small       | Kubernetes |   1 |  2048 |  15 | Yes        |
| g3.k3s.medium  | Medium      | Kubernetes |   2 |  4096 |  15 | Yes        |
| g3.k3s.large   | Large       | Kubernetes |   4 |  8192 |  15 | Yes        |
| g3.k3s.xlarge  | Extra Large | Kubernetes |   6 | 16384 |  15 | Yes        |
| g3.k3s.2xlarge | 2X Large    | Kubernetes |   8 | 32768 |  15 | Yes        |
+----------------+-------------+------------+-----+-------+-----+------------+
```

**Comment by alejandrojnm** [comment]
Hi @dirsigler you can use in this way 

```tf
data "civo_instances_size" "small" {
    filter {
        key = "type"
        values = ["kubernetes"]
    }
}
```

**Comment by dirsigler** [comment]
> Hi @dirsigler you can use in this way

Ok, this works too.
But still this does not change anything on the problem.

In my opinion there should be some kind of better documentation on which sizes are available in the provider documentation.
Either by adding the data source to the [Example](https://registry.terraform.io/providers/civo/civo/latest/docs/data-sources/kubernetes_cluster#example-usage) or providing further information in a linked site.

Also providing a table in the bottom of the resource documentation can be a working solution.

What do you think? @alejandrojnm

**Comment by andyjeffries** [comment]
I agree, this comes down to "the code works and the example works" but the Developer eXperience is lacking.
