### ISSUE TITLE
Mark password and similar sensitive fields as Terraform Sensitive Data

### ISSUE THREAD

**Issue by faem** [civo/terraform-provider-civo#51]
The `initial_password` field in `civo_instance` is a sensitive field. So it should be marked as Sensitive. 

Ref: 
https://github.com/civo/terraform-provider-civo/blob/master/civo/resource_instance.go#L121-L124
https://www.terraform.io/docs/language/state/sensitive-data.html

**Comment by tamalsaha** [comment]
Kubeconfig in Cluster resource will be another one.

**Comment by tamalsaha** [comment]
Done https://github.com/civo/terraform-provider-civo/issues/57
