### ISSUE TITLE
`civo_kubernetes_cluster` scale up is not working as expected

### ISSUE THREAD

**Issue by faem** [civo/terraform-provider-civo#52]
First created a `civo_kubernetes_cluster` resource using the following tf file:
```
resource "civo_kubernetes_cluster" "my-cluster" {
    name = "my-cluster"
    num_target_nodes = 3
    target_nodes_size = "g3.k3s.xsmall"
}
```

Then updated the `num_target_nodes` field to `5` and applied again.
```
resource "civo_kubernetes_cluster" "my-cluster" {
    name = "my-cluster"
    num_target_nodes = 5
    target_nodes_size = "g3.k3s.xsmall"
}
```

Expected to see 5 nodes on the cluster. But it only scales up to 4 and the `terraform apply` command returns successfully.

**Comment by zulh-civo** [comment]
I can confirm this issue happened to me as well. But not when I'm using Civo.com web UI. I will take a look.
