### ISSUE TITLE
Can't update the size of `civo_isntance`

### ISSUE THREAD

**Issue by faem** [civo/terraform-provider-civo#53]
First created a `civo_instance` using the following tf file:
```
resource "civo_instance" "my-test-instance" {
    hostname = "kubeform-test"
    tags = ["python", "nginx"]
    notes = "this is a note for the server"
    size = "g3.xsmall"
    template = "8eb48e20-e5db-49fe-9cdf-cc8f381c61c6"  
}
```

Then updated the `size` to `g3.large`. 

```
resource "civo_instance" "my-test-instance" {
    hostname = "kubeform-test"
    tags = ["python", "nginx"]
    notes = "this is a note for the server"
    size = "g3.large"
    template = "8eb48e20-e5db-49fe-9cdf-cc8f381c61c6"  
}
```

Got this error from `terraform apply`:

```
civo_instance.my-test-instance: Refreshing state... [id=f5d9f705-3cbb-4049-9423-4fd90076d674]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # civo_instance.my-test-instance will be updated in-place
  ~ resource "civo_instance" "my-test-instance" {
        id                 = "f5d9f705-3cbb-4049-9423-4fd90076d674"
      ~ size               = "g3.xsmall" -> "g3.large"
        tags               = [
            "nginx",
            "python",
        ]
        # (17 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
civo_instance.my-test-instance: Modifying... [id=f5d9f705-3cbb-4049-9423-4fd90076d674]
╷
│ Error: [WARN] An error occurred while resizing the instance f5d9f705-3cbb-4049-9423-4fd90076d674
│ 
│   with civo_instance.my-test-instance,
│   on main.tf line 14, in resource "civo_instance" "my-test-instance":
│   14: resource "civo_instance" "my-test-instance" {
│ 
╵
```

**Comment by kaihoffman** [comment]
I think  we've identified the issue @zulh-civo . Any chance you kept the instance around? Are you able to let me know if it's actually upgraded behind the scenes if you refresh? I only ask because the error I think this is bubbling up comes from a different part of the code, after the resize is complete.

**Comment by tamalsaha** [comment]
Sorry, we don't have the instance anymore.

**Comment by kaihoffman** [comment]
@tamalsaha no worries, we're implementing a fix now regardless. In case @zulh-civo still has his instance around I'd be curious but purely out of a desire to find out if I was right, haha.

**Comment by zulh-civo** [comment]
The API team had pushed a fix related to the API error and there's no more error when resizing instance using Civo.com or API. I also have created #61 to fix a small Terraform provider bug when resizing instance.

However we noticed that the instance resize didn't take place properly. Meaning, the update request went through the API and get saved successfully in our database but the resize process is not triggering. We suspect there's a glitch in our [CivoStack operator](https://www.civo.com/blog/new-year-new-york-new-civostack) and our infra team is looking at this issue.

That's an infra issue and we are tracking it internally. While it's kinda related to this issue, I don't think it's a blocker for us to merge #61 and publish a new Terraform provider release.
