### ISSUE TITLE
public key in SSH should not be marked sensitive

### ISSUE THREAD

**Issue by tamalsaha** [civo/terraform-provider-civo#58]
https://github.com/civo/terraform-provider-civo/blob/e82f7ce8bc846c5b7bc4040a60aecc974d42a378/civo/resource_ssh.go#L27

**Comment by saiyam1814** [comment]
Cool @zulh-civo can this also be included in the same PR ?

**Comment by zulh-civo** [comment]
@saiyam1814 for much clear tracking and make reviewers' work easier, I prefer we have separate PR. Meaning, this issue will be linked to another PR. Release wise, we can release them together, no worry.

**Comment by saiyam1814** [comment]
ok makes sense
