### ISSUE TITLE
Change default node size to "g3.k3s.medium"

### ISSUE THREAD

**Issue by zulh-civo** [civo/terraform-provider-civo#65]
The CLI [is using](https://github.com/civo/cli/blob/24baf1f7c4be24d5c3b7e149406451badfd89d20/cmd/kubernetes.go#L76) "g3.k3s.medium" as default node size when creating a cluster. But this Terraform provider [is using](https://github.com/civo/terraform-provider-civo/blob/076005617496bc63a5cfe523a61b611d0ae32c4e/civo/resource_kubernetes_cluster.go#L255) "g3.k3s.small" as default.

Which one should be the default when user launch a cluster without providing the node size? @andyjeffries @saiyam1814 

I guess "g3.k3s.medium" should be the default. Is that correct?

**Comment by andyjeffries** [comment]
I think medium is best - if people launch a small they may have a bad experience due to some fairly hefty apps in the App Store. If they want to launch a smaller one they can choose it with options.

**Comment by saiyam1814** [comment]
+1 to what Andy said
